# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: GenDiff CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          make install
          make build
          make test --passWithNoTests
        env:
          CI: true
      - name: Run linter
        run: |
          make lint
      - name: Test & publish code coverage
        uses: marsam/codeclimate-action@master
        env:
          CC_TEST_REPORTER_ID: 54bf158710ddda443bfb8d2dc83ec7ea1afbd9571916c81639cdaa577fde9c8b
        with:
          coverageCommand: make test-coverage
          debug: true
